/**
 * Unit tests — ADR index staleness check (V13-OPS)
 *
 * Tests the pure helper functions from scripts/check-adr-index.mjs:
 *   - parseAdrContent: extract title/date/status from ADR markdown
 *   - pad: column padding utility
 *   - buildAdrIndex: generate README.md table content
 */

import { describe, it, expect } from "vitest";

// ── Inline copies of exported pure helpers from check-adr-index.mjs ──────────

function parseAdrContent(fileText: string, fileName: string) {
  const lines = fileText.split("\n");

  const titleLine = lines.find((l) => l.startsWith("# "));
  const title = titleLine
    ? titleLine.replace(/^#\s*ADR-\d+[:\s—-]+\s*/, "").trim()
    : fileName.replace(".md", "");

  const datePatterns = [
    /^\*\*Date:\*\*\s*(\d{4}-\d{2}-\d{2})/,
    /^\|\s*\*?\*?Date\*?\*?\s*\|\s*(\d{4}-\d{2}-\d{2})/,
  ];
  let date = "—";
  for (const l of lines) {
    for (const pat of datePatterns) {
      const m = l.match(pat);
      if (m) { date = m[1]; break; }
    }
    if (date !== "—") break;
  }

  const statusPatterns = [/^\*\*Status:\*\*\s*(.+)/, /^\|\s*\*?\*?Status\*?\*?\s*\|\s*([^|]+)\|/];
  let status = "—";
  for (const l of lines) {
    for (const pat of statusPatterns) {
      const m = l.match(pat);
      if (m) { status = m[1].trim(); break; }
    }
    if (status !== "—") break;
  }

  return { file: fileName, title, date, status };
}

function pad(str: string, width: number): string {
  return str + " ".repeat(Math.max(0, width - str.length));
}

function buildAdrIndex(adrs: Array<{ file: string; title: string; date: string; status: string }>): string {
  const linkWidth = Math.max(...adrs.map((a) => `[${a.file.replace(".md", "")}](${a.file})`.length), 3);
  const titleWidth = Math.max(...adrs.map((a) => a.title.length), 5);
  const dateWidth = Math.max(...adrs.map((a) => a.date.length), 4);
  const statusWidth = Math.max(...adrs.map((a) => a.status.length), 6);

  const header = `| ${pad("ADR", linkWidth)} | ${pad("Title", titleWidth)} | ${pad("Date", dateWidth)} | ${pad("Status", statusWidth)} |`;
  const sep = `| ${"-".repeat(linkWidth)} | ${"-".repeat(titleWidth)} | ${"-".repeat(dateWidth)} | ${"-".repeat(statusWidth)} |`;
  const rows = adrs.map((a) => {
    const adrNum = a.file.replace(/^(ADR-\d+).*\.md$/, "$1");
    const link = `[${adrNum}](${a.file})`;
    return `| ${pad(link, linkWidth)} | ${pad(a.title, titleWidth)} | ${pad(a.date, dateWidth)} | ${pad(a.status, statusWidth)} |`;
  });

  return [
    "# ADR Index",
    "",
    "> Architectural Decision Records for FamilyDashBoard.",
    "> Auto-generated by `scripts/generate-adr-index.mjs` — do not edit manually.",
    "",
    header,
    sep,
    ...rows,
    "",
  ].join("\n");
}

// ── parseAdrContent ───────────────────────────────────────────────────────────

describe("parseAdrContent — extract ADR metadata (V13-OPS)", () => {
  it("parses title from first heading stripping ADR number prefix", () => {
    const text = "# ADR-001: No Shadow DOM\n\n**Date:** 2026-04-17\n**Status:** Accepted\n";
    const result = parseAdrContent(text, "ADR-001-shadow-dom.md");
    expect(result.title).toBe("No Shadow DOM");
  });

  it("parses title with em-dash separator", () => {
    const text = "# ADR-007 — News Aggregation Strategy\n\n**Date:** 2026-07-10\n**Status:** Accepted\n";
    const result = parseAdrContent(text, "ADR-007-news.md");
    expect(result.title).toBe("News Aggregation Strategy");
  });

  it("parses date from bold-inline format", () => {
    const text = "# ADR-001: Test\n\n**Date:** 2026-04-17\n**Status:** Accepted\n";
    expect(parseAdrContent(text, "ADR-001.md").date).toBe("2026-04-17");
  });

  it("parses date from plain table cell", () => {
    const text = "# ADR-010: Test\n\n| Date       | 2025-07-01 |\n| Status     | Accepted   |\n";
    expect(parseAdrContent(text, "ADR-010.md").date).toBe("2025-07-01");
  });

  it("parses date from bold table cell", () => {
    const text = "# ADR-010: Test\n\n| **Date**   | 2025-07-01 |\n| **Status** | Accepted   |\n";
    expect(parseAdrContent(text, "ADR-010.md").date).toBe("2025-07-01");
  });

  it("returns — for date when missing", () => {
    const text = "# ADR-001: Test\n\n**Status:** Accepted\n";
    expect(parseAdrContent(text, "ADR-001.md").date).toBe("—");
  });

  it("parses status from bold-inline format", () => {
    const text = "# ADR-001: Test\n\n**Date:** 2026-04-17\n**Status:** Proposed\n";
    expect(parseAdrContent(text, "ADR-001.md").status).toBe("Proposed");
  });

  it("parses status from table cell", () => {
    const text = "# ADR-010: Test\n\n| Date   | 2025-07-01 |\n| Status | Deprecated |\n";
    expect(parseAdrContent(text, "ADR-010.md").status).toBe("Deprecated");
  });

  it("returns — for status when missing", () => {
    const text = "# ADR-001: Test\n\n**Date:** 2026-04-17\n";
    expect(parseAdrContent(text, "ADR-001.md").status).toBe("—");
  });

  it("falls back to filename as title when no # heading", () => {
    const text = "**Date:** 2026-04-17\n**Status:** Accepted\n";
    expect(parseAdrContent(text, "ADR-099-test.md").title).toBe("ADR-099-test");
  });

  it("preserves file name in result", () => {
    const text = "# ADR-001: Test\n**Date:** 2026-04-17\n**Status:** Accepted\n";
    expect(parseAdrContent(text, "ADR-001-shadow-dom.md").file).toBe("ADR-001-shadow-dom.md");
  });
});

// ── pad ───────────────────────────────────────────────────────────────────────

describe("pad — column padding utility (V13-OPS)", () => {
  it("pads a short string to the target width", () => {
    expect(pad("abc", 6)).toBe("abc   ");
  });

  it("returns the string unchanged when already at width", () => {
    expect(pad("abcdef", 6)).toBe("abcdef");
  });

  it("returns the string unchanged when wider than target", () => {
    expect(pad("abcdefg", 6)).toBe("abcdefg");
  });

  it("handles empty string", () => {
    expect(pad("", 3)).toBe("   ");
  });
});

// ── buildAdrIndex ─────────────────────────────────────────────────────────────

describe("buildAdrIndex — generate README.md content (V13-OPS)", () => {
  const ONE_ADR = [
    { file: "ADR-001-shadow-dom.md", title: "No Shadow DOM in FdbCard", date: "2026-04-17", status: "Accepted" },
  ];

  it("includes the standard ADR index header", () => {
    const out = buildAdrIndex(ONE_ADR);
    expect(out).toContain("# ADR Index");
    expect(out).toContain("Auto-generated by `scripts/generate-adr-index.mjs`");
  });

  it("includes the ADR link in the table", () => {
    const out = buildAdrIndex(ONE_ADR);
    expect(out).toContain("[ADR-001](ADR-001-shadow-dom.md)");
  });

  it("includes the title in the table", () => {
    const out = buildAdrIndex(ONE_ADR);
    expect(out).toContain("No Shadow DOM in FdbCard");
  });

  it("includes date and status in the table", () => {
    const out = buildAdrIndex(ONE_ADR);
    expect(out).toContain("2026-04-17");
    expect(out).toContain("Accepted");
  });

  it("produces deterministic output for same input", () => {
    expect(buildAdrIndex(ONE_ADR)).toBe(buildAdrIndex(ONE_ADR));
  });

  it("produces different output when a new ADR is added", () => {
    const twoAdrs = [
      ...ONE_ADR,
      { file: "ADR-002-zero-deps.md", title: "Zero Client-Side Deps", date: "2026-04-18", status: "Accepted" },
    ];
    expect(buildAdrIndex(ONE_ADR)).not.toBe(buildAdrIndex(twoAdrs));
  });

  it("produces different output when title changes", () => {
    const modified = [{ ...ONE_ADR[0], title: "Updated Title" }];
    expect(buildAdrIndex(ONE_ADR)).not.toBe(buildAdrIndex(modified));
  });

  it("ends with a single newline", () => {
    const out = buildAdrIndex(ONE_ADR);
    expect(out.endsWith("\n")).toBe(true);
    expect(out.endsWith("\n\n")).toBe(false);
  });
});
